language: ruby
rvm:
  - 1.9.3
  - 2.2.3
  - 2.3.0
  - jruby-1.7.22
  - jruby-9.0.4.0
jdk:
  - openjdk7
env:
  - TEST_UNIT="~> 2.5"
  - TEST_UNIT="~> 3.0"
  - TEST_UNIT="~> 3.1"
matrix:
  include:
    - rvm: 1.8.7
      env: TEST_UNIT="~> 2.5"
