language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - jruby-1.6.8
  - jruby-1.7.16
jdk:
  - openjdk7
env:
  - TEST_UNIT="~> 2.5.5"
  - TEST_UNIT="~> 3.0.9"
matrix:
  exclude:
    - rvm: 1.8.7
      env: TEST_UNIT="~> 3.0.9"
    - rvm: jruby-1.6.8
      env: TEST_UNIT="~> 3.0.9"
